# Generated by Django 3.1.1 on 2020-09-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=300)),
                ('product_image', models.ImageField(upload_to='blog_images/')),
                ('product_price', models.TextField()),
            ],
        ),
    ]
